name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "🎉 Running Snyk"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run Snyk Analysis
        run: synk code test --severity-threshold=high
      - name: Run Snyk Open source dependencies
        run: synk test --severity-threshold=high
      - name: Monitor snyk
        run: synk monitor
